<a href="https://colab.research.google.com/github/abidhasan5135-maker/PythonsLibrary/blob/main/NumPy_and_Pandas_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a id="overview"></a>
## Course Overview
### 1. Introduction to NumPy and Pandas for Data Science
This section introduces the basics of NumPy and Pandas for data science.

#### 1.1 NumPy Basics
Learn how to create arrays and perform basic array operations in NumPy.

#### 1.2 Pandas Basics
Get familiar with creating DataFrames and performing basic operations.

### 2. Mathematical Operations in NumPy
Explore mathematical operations on NumPy arrays.

#### 2.1 Element-wise Operations
Learn element-wise addition, multiplication, and other operations.

#### 2.2 Broadcasting in NumPy
Understanding how broadcasting works in NumPy for array operations.

### 3. Statistical Operations in NumPy
Perform statistical operations like mean, standard deviation, etc.

### 4. Data Manipulation in Pandas
Learn how to manipulate data using Pandas DataFrames.

#### 4.1 Creating DataFrames
Learn how to create and manipulate DataFrames.

#### 4.2 DataFrame Operations
Perform basic operations like filtering, grouping, and sorting in Pandas.

# Part 0 · Getting Started

<a id="sec-01"></a>
## 1. Setup — Install Packages & Import Libraries

In [2]:
# Install required packages (run this first in Google Colab)
!pip install numpy pandas matplotlib

# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

NumPy version: 2.1.3
Pandas version: 2.2.3


# Part 1 · NumPy Fundamentals

<a id="sec-02"></a>
## 2. Creating NumPy Arrays (1D & 2D)

In [ ]:
# Creating NumPy arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print("1D Array:", arr1)
print("2D Array:\n", arr2)
print("Array shape:", arr1.shape)
print("Array dtype:", arr1.dtype)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Array shape: (5,)
Array dtype: int64


<a id="sec-03"></a>
## 3. Array Creation Functions — zeros, ones, arange, linspace

In [ ]:
# Different ways to create arrays
zeros_array = np.zeros((3, 4), dtype=int)
ones_array = np.ones((2, 3), dtype= int)
range_array = np.arange(0, 10, 2)
linspace_array = np.linspace(0, 1, 5)

print("Zeros array:\n", zeros_array)
print("Ones array:\n", ones_array)
print("Range array:", range_array)
print("Linspace array:", linspace_array)

Zeros array:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Ones array:
 [[1 1 1]
 [1 1 1]]
Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]


<a id="sec-04"></a>
## 4. Math, Statistics & Broadcasting

In [ ]:
# Mathematical operations on arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 3, 4, 5, 6])

# Element-wise operations
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Power:", a ** 2)
print("Square root:", np.sqrt(a))

# Statistical operations
print("Mean:", np.mean(a))
print("Standard deviation:", np.std(a))
print("Min:", np.min(a))
print("Max:", np.max(a))

# Broadcasting example
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])
result = matrix + vector
print("Broadcasting result:\n", result)

Addition: [ 3  5  7  9 11]
Subtraction: [-1 -1 -1 -1 -1]
Multiplication: [ 2  6 12 20 30]
Power: [ 1  4  9 16 25]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Mean: 3.0
Standard deviation: 1.4142135623730951
Min: 1
Max: 5
Broadcasting result:
 [[11 22 33]
 [14 25 36]]


<a id="sec-05"></a>
## 5. Indexing & Slicing Arrays

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Indexing
print("Element at index 2:", arr[2])

# Slicing
print("Sliced array (from index 1 to 3):", arr[1:4])

# 2D array slicing
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Sliced 2D array (first two rows):\n", arr_2d[:2])

Element at index 2: 30
Sliced array (from index 1 to 3): [20 30 40]
Sliced 2D array (first two rows):
 [[1 2 3]
 [4 5 6]]


# Part 2 · Pandas Fundamentals

<a id="sec-06"></a>
## 6. Creating a DataFrame from a Dictionary

In [ ]:
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [24, 27, 22],
        'City': ['New York', 'Los Angeles', 'Chicago']}

df = pd.DataFrame(data)
print("DataFrame:\n", df)

DataFrame:
       Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago


<a id="sec-07"></a>
## 7. Inspecting a DataFrame — info, describe, head, tail, dtypes

In [ ]:
# Basic DataFrame information
print("\nDataFrame Info:")
print(df.info())
print("\nDataFrame Description:")
print(df.describe())
print("\nDataFrame Shape:", df.shape)
print("Column names:", df.columns.tolist())
# Display first 5 rows
print("First 5 rows of the dataset:")
print(df.head())
# Display last 5 rows
print("\nLast 5 rows of the dataset:")
print(df.tail())
# Check data types
print("\nData Types:")
print(df.dtypes)


DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None

DataFrame Description:
             Age
count   3.000000
mean   24.333333
std     2.516611
min    22.000000
25%    23.000000
50%    24.000000
75%    25.500000
max    27.000000

DataFrame Shape: (3, 3)
Column names: ['Name', 'Age', 'City']
First 5 rows of the dataset:
      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago

Last 5 rows of the dataset:
      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago

Data Types:
Name    object
Age      int64
City    object
dtype: object


<a id="sec-08"></a>
## 8. Selecting Single & Multiple Columns

In [ ]:
# Accessing a single column
print("Names column:\n", df['Name'])

# Accessing multiple columns
print("\nName and Age columns:\n", df[['Name', 'Age']])


Names column:
 0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

Name and Age columns:
       Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22


<a id="sec-09"></a>
## 9. Converting a NumPy Array into a DataFrame

In [1]:
# Convert NumPy array to DataFrame
np_array = np.random.randn(5, 3)
df_from_array = pd.DataFrame(np_array, columns=['A', 'B', 'C'])
print("DataFrame from NumPy array:")
print(df_from_array)

NameError: name 'np' is not defined

<a id="sec-10"></a>
## 10. Grouping & Aggregation — Sales by Region

In [ ]:
# Create sample sales data
sales_data = {
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
    'Product': ['A', 'A', 'B', 'B', 'A', 'B', 'A', 'B'],
    'Sales': [100, 150, 200, 120, 110, 180, 190, 140],
    'Quantity': [10, 15, 20, 12, 11, 18, 19, 14]
}
sales_df = pd.DataFrame(sales_data)
print("Sales DataFrame:")
print(sales_df)

# Group by operations
Product_sales = sales_df.groupby('Product')['Sales'].sum()
print("\nSales by Product:")
print(Product_sales)


Sales DataFrame:
  Region Product  Sales  Quantity
0  North       A    100        10
1  South       A    150        15
2   East       B    200        20
3   West       B    120        12
4  North       A    110        11
5  South       B    180        18
6   East       A    190        19
7   West       B    140        14

Sales by Product:
Product
A    550
B    640
Name: Sales, dtype: int64


# Part 3 · Working with a Real Dataset

<a id="sec-11"></a>
## 11. Loading a CSV from Google Drive

In [10]:
from google.colab import drive
drive.mount('/content/drive')

import warnings
warnings.filterwarnings('ignore')


Mounted at /content/drive


In [11]:
file_path = '/content/drive/MyDrive/SKILL_MOR_4/diabetes.csv'
df = pd.read_csv(file_path)  # No header in raw CSV
print("Dataset loaded successfully. Shape:", df.shape)

Dataset loaded successfully. Shape: (768, 9)


<a id="sec-12"></a>
## 12. Uploading a CSV Manually (files.upload)

In [ ]:
from google.colab import files
uploaded = files.upload()

# Load the uploaded file
import io
df = pd.read_csv(io.BytesIO(uploaded['diabetes.csv']))

<a id="sec-14"></a>
## 13. Exploring the Dataset — head, info, describe

In [12]:
# Quick overview
print(df.head())
print("\nDataset info:")
print(df.info())

# Basic statistics
print("\nDescriptive statistics:")
print(df.describe())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  

Dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose       

<a id="sec-15"></a>
## 15. Checking for Missing Values

In [ ]:
#missing values
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64


<a id="sec-18"></a>
# Part 4 · Practice
## 16.Students Performance Dataset

Upload **StudentsPerformance.csv** to Colab, then answer the following questions in the cell below by writing your code under each comment.

**Columns:** `gender`, `race/ethnicity`, `parental level of education`, `lunch`, `test preparation course`, `math score`, `reading score`, `writing score`

In [3]:
# ============================================================
# Practice: Students Performance Dataset
# ============================================================

import numpy as np
import pandas as pd

# Load the dataset


# Q1. Display the first 5 rows of the dataset, then print its shape

# Q2. Print the average (mean) math score, reading score and writing score


In [14]:
file_location ='/content/drive/MyDrive/SKILL_MOR_4/StudentsPerformance.csv'
df = pd.read_csv(file_location)

In [15]:
# Q1. Display the first 5 rows of the dataset, then print its shape
#--------------SOLUTION:----------------:

print("The First 5 rows of the dataset: \n", df.head())
print("its shape: ", df.shape)

The First 5 rows of the dataset: 
    gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75  
its shape:  (1000, 8)


In [16]:
# Q2. Print the average (mean) math score, reading score and writing score.
#--------------SOLUTION:----------------:

print("The average (mean) math score: ", df['math score'].mean())
print("The average (mean) reading score: ", df['reading score'].mean())
print("The average (mean) writing score: ", df['writing score'].mean())





The average (mean) math score:  66.089
The average (mean) reading score:  69.169
The average (mean) writing score:  68.054
